export const categories = [
  {
    id: 1,
    title: "Baby Care",
    image: "https://cdn.chefaa.com/filters:format(webp)/public/uploads/categories/s4MJ24p5E0jS4ZANi9XtDcBndSWHEkvTO7saPR2f.png",
    slug: "baby-care",
    created_at: "2019-12-10 03:00:32",
    updated_at: "2022-01-02 12:52:05",
    deleted_at: null,
  },
  {
    id: 2,
    title: "Women Care",
    image: "https://cdn.chefaa.com/filters:format(webp)/public/uploads/categories/Y91q4J3BSrfrC5GiotLnRPZngFuN4GyAi6hvF1iK.png",
    slug: "women-care",

    created_at: "2019-12-10 03:03:44",
    updated_at: "2022-11-11 17:23:36",
    deleted_at: null,
  },
  {
    id: 3,
    title: "Men Care",
    image: "https://cdn.chefaa.com/filters:format(webp)/public/uploads/categories/YiOepQonjSsqsjSrdjOFpiDSqfEroSnmGIPQfcuv.png",
    created_at: "2019-12-10 03:04:26",
    updated_at: "2022-11-11 17:25:55",
    slug: "men-care",
    deleted_at: null,
  },
];

export const products = [
  {
    id: 1,
    title: "Neutrogena | Deep Clean Gel Facial Wash | 200ml",
    creation_type: "single",
    center_pharmacy_id: 640,
    seller: 1,
    seller_name: "Chefaa store",
    status: "active",
    not_indexing: 1,
    low_stock: 0,
    is_outofstock: 1,
    can_installment: 0,
    need_prescription: 0,
    barcode: "3574660245844",
    sku: null,
    verified: "0",
    pharmacy_branch_id: null,
    quantity: 0,
    max_quantity: 0,
    main_category_id: 2,
    category_id: 3,
    brand_id: 14,
    store_order_item_id: 2,
    slug: "neutrogena-deep-clean-gel-facial-wash-200ml",
    images: [
      "https://cdn.chefaa.com/public/uploads/products/neutrogena-deep-clean-gel-facial-wash-200ml-01662988102.png",
    ],
    alt_images: ["غسول نيتروجينا للبشرة الدهنية الاصفر، غسول جل عميق المفعول"],
    coupon_description: '{"en":"save","ar":"وفر"}',
    views: 0,
    purchase_count: 45,
    description:
      "Cleanses deep down into the pores. Dissolves dirt, oil and make-up. Removes dead surface skin that can make your complexion dry, rough and dull.",
    highlights_ar:
      "<ul><li>غسول نيتروجينا للبشرة الدهنية الاصفر، غسول جل عميق المفعول</li></ul>",
    highlights_en:
      "<ul><li>Neutrogena Deep Clean Gel Facial Wash - 200ml</li></ul>",
    not_return: 0,
    price: 135,
    cost_price: 118,
    discount: 5,
    bundle_tag: null,
    discount_type: "percent",
    bigsave_discount: 0,
    sorting_keyword_en: null,
    sorting_keyword_ar: null,
    start_date: "2022-10-04",
    start_time: "15:41:00",
    end_date: null,
    end_time: null,
    scheduled_discount_type: null,
    scheduled_discount: null,
    scheduled_bundle_tag: null,
    country_id: 1,
    created_at: "2019-12-31 04:05:07",
    updated_at: "2023-04-16 13:05:18",
    deleted_at: null,
    sorting: null,
    gameball_points: null,
    level_one_id: 3,
    flow_type: 1,
  },
  {
    id: 2,
    title: "Sofy | Maxi Thick Long Pads | 16 Pcs",
    creation_type: "single",
    center_pharmacy_id: null,
    seller: 1,
    seller_name: null,
    status: "active",
    not_indexing: 0,
    low_stock: 0,
    is_outofstock: 1,
    can_installment: 0,
    need_prescription: 0,
    barcode: "6223004790133",
    sku: null,
    verified: "0",
    pharmacy_branch_id: null,
    quantity: 0,
    max_quantity: 0,
    main_category_id: 1,
    category_id: 2,
    brand_id: 11,
    store_order_item_id: 4,
    slug: "sofy-maxi-thick-long-pads-16-pcs",
    images: ["https://cdn.chefaa.com/uploads/products/NHyfHRB1QkTs56QKJVetEa31qUjKkKplbiSDJCG7.jpeg"],
    alt_images: ["سوفي ماكسي فوط طويلة سميكة - 16 قطعة"],
    coupon_description: "",
    views: 0,
    purchase_count: 377,
    description: "Sofy Maxi Thick Long Pads - 16 Pcs",
    highlights_ar: "<ul><li>Sofy ماكسي فوط طويلة سميكة - 16 قطعة</li></ul>",
    highlights_en: "<ul><li>Sofy Maxi Thick Long Pads - 16 Pcs</li></ul>",
    not_return: 0,
    price: 40,
    cost_price: 0,
    discount: null,
    bundle_tag: null,
    discount_type: null,
    bigsave_discount: 0,
    sorting_keyword_en: null,
    sorting_keyword_ar: null,
    start_date: null,
    start_time: null,
    end_date: null,
    end_time: null,
    scheduled_discount_type: null,
    scheduled_discount: null,
    scheduled_bundle_tag: null,
    country_id: 1,
    created_at: "2019-12-31 04:29:50",
    updated_at: "2023-03-13 12:41:13",
    deleted_at: null,
    sorting: null,
    gameball_points: null,
    level_one_id: 4,
    flow_type: 2,
  },
  {
    id: 3,
    title: "One Touch | Select Test | 50 Strips",
    creation_type: "single",
    center_pharmacy_id: null,
    seller: 1,
    seller_name: null,
    status: "active",
    not_indexing: 0,
    low_stock: 0,
    is_outofstock: 0,
    can_installment: 0,
    need_prescription: 0,
    barcode: "7613427015620",
    sku: null,
    verified: "0",
    pharmacy_branch_id: null,
    quantity: 25,
    max_quantity: 0,
    main_category_id: 1,
    category_id: 1,
    brand_id: 266,
    store_order_item_id: 2,
    slug: "one-touch-select-test-50-strips",
    images: ["https://cdn.chefaa.com/uploads/products/1626447832one-touch-select-test-50-stripsjpg"],
    alt_images: ["وان تاتش سيليكت شرائط تحليل السكر لقياس السكر 50 شريط"],
    canonical_tag:
      "https://chefaa.com/eg-ar/waffarProduct/one-touch-select-test-50-strips-opxq",
    coupon_description: "",
    views: 0,
    purchase_count: 19,
    description:
      "One Touch 50 blood sugar test strips are ideal for home use for diabetics and can be used as a clinical test by health experts for use on the finger, palm, or palm of the hand. Pack contains 50 strips",
    highlights_ar:
      "<ul><li>تتميز أنها سهلة الاستخدام.</li><li>تتميز بجودتها ودقة نتائجها.</li><li>تتميز أنها صغيرة الحجم ومصنوعة من خامات عالية الجودة.</li><li>تحتاج الشرائط إلى عينة دم قليلة تصل إلى 0.5 مل فقط لتحديد مستوى السكر في الدم.</li><li>تتوافق شرائط تحليل السكر مع تكنولوجيا سحب العينة التلقائي الموجود في جهاز السكر وذلك لضمان توفير قياس دقيق لنسبة السكر.</li><li>مناسبة للاستخدام الذاتي دون الحاجة إلى المساعدة.</li><li>تاريخ الانتهاء مكتوب على العبوة من الخارج.</li><li>تتميز شرائط تحليل السكر بأنها معقمة وجاهزة للاستخدام.</li><li>مناسبة لمعظم أنواع أجهزة وان تاتش سيليكت لقياس السكر.</li><li>يمكن استخدامها من قبل كل الأعمار.</li><li>تتميز بسعرها المناسب الملائم للجميع.</li></ul>",
    highlights_en: "<ul><li>   </li></ul>",
    not_return: 0,
    price: 330,
    cost_price: 220,
    discount: null,
    bundle_tag: null,
    discount_type: null,
    bigsave_discount: 0,
    sorting_keyword_en: null,
    sorting_keyword_ar: null,
    start_date: null,
    start_time: null,
    end_date: null,
    end_time: null,
    scheduled_discount_type: null,
    scheduled_discount: null,
    scheduled_bundle_tag: null,
    country_id: 1,
    created_at: "2019-12-31 21:12:39",
    updated_at: "2023-04-05 13:39:33",
    deleted_at: null,
    sorting: null,
    gameball_points: null,
    level_one_id: 7,
    flow_type: 2,
  },
  {
    id: 4,
    title: "Tempo Cool | Infant Fever Gel Cooling | 4 Sheet",
    creation_type: "single",
    center_pharmacy_id: null,
    seller: 1,
    seller_name: null,
    status: "active",
    not_indexing: 0,
    low_stock: 0,
    is_outofstock: 0,
    can_installment: 0,
    need_prescription: 0,
    barcode: "6224007240281",
    sku: null,
    verified: "0",
    pharmacy_branch_id: null,
    quantity: 3,
    max_quantity: 0,
    main_category_id: 4,
    category_id: 1,
    brand_id: null,
    store_order_item_id: 2,
    slug: "tempo-cool-infant-fever-gel-cooling-sheet",
    images: [
      "https://cdn.chefaa.com/public/uploads/products/1621086591tempo-cool-infant-fever-gel-cooling-4-sheet-chefaajpg",
    ],
    alt_images: ["كمادات جل باردة خافضة للحرارة للأطفال والرضع والرضع"],
    canonical_tag: "",
    coupon_description: "",
    views: 0,
    purchase_count: 182,
    description: "Tempo Cool | Infant Fever Gel Cooling | 4 Sheet",
    highlights_ar:
      "<ul><li>تيمبو كول | كمادات الجل للأطفال والرضع | 4 أكياس</li></ul>",
    highlights_en:
      "<ul><li>Tempo Cool | Infant Fever Gel Cooling | 4 Sheet</li></ul>",
    not_return: 0,
    price: 32,
    cost_price: 0,
    discount: null,
    bundle_tag: null,
    discount_type: null,
    bigsave_discount: 0,
    sorting_keyword_en: null,
    sorting_keyword_ar: null,
    start_date: null,
    start_time: null,
    end_date: null,
    end_time: null,
    scheduled_discount_type: null,
    scheduled_discount: null,
    scheduled_bundle_tag: null,
    country_id: 1,
    created_at: "2020-01-01 00:00:33",
    updated_at: "2023-04-15 15:16:40",
    deleted_at: null,
    sorting: null,
    gameball_points: null,
    level_one_id: 1,
    flow_type: 2,
  },
];
